# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PodpinaczKrok3
                                 A QGIS plugin
 Plugin porządkujący dane do warstw ostatecznych
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-09
        copyright            : (C) 2021 by Kamil Drejer
        email                : klamot@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Kamil Drejer'
__date__ = '2021-04-09'
__copyright__ = '(C) 2021 by Kamil Drejer'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PodpinaczKrok3 class from file PodpinaczKrok3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .podpinacz_krok_3 import PodpinaczKrok3Plugin
    return PodpinaczKrok3Plugin()
